name: Ping LINE Bot (Render)

on:
  schedule:
    - cron: '55 8 * * 1-5'  # 平日17:55（日本時間 → UTCに変換済み）
  workflow_dispatch:  # 手動実行も可能

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to /ping
        run: curl -s https://line-bot-auto.onrender.com/ping
